.idea/artifacts/asciidoctor_intellij_jar.xml, .idea/artifacts/asciidoctor_intellij_zip.xml
They can be used to build plugin in TeamCity
=> Define idea artifacts for plugin

META-INF/plugin.xml
it does not compile for earlier versions...
=> Proper since-build

src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java, src/main/java/org/asciidoc/intellij/editor/LazyApplicationPoolExecutor.java
fixes #65 and much more...
javax.swing.JEditorPane#setText is really expensive, perhaps there is a way how to not do it on EDT?
=> render only when the preview is visible

META-INF/plugin.xml, src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeLink.java, src/test/java/org/asciidoc/intellij/actions/asciidoc/MakeLinkTest.java
Adds a button to insert a hyperlink in the editor.
Solves #38.
=> Added "Make Link" feature (Issue 38).

src/main/java/org/asciidoc/intellij/AsciiDocLanguage.java
Added null check before dealing with the IntelliJ APIs
=> Fixes #110: AssertionError in JBoss Forge projects

src/main/java/org/asciidoc/intellij/actions/asciidoc/ToggleSoftWrapsAction.java, src/main/resources/META-INF/plugin.xml
PR for #221 to add soft wrap toggle button to the editor toolbar.
=> Added soft wrap button to editor toolbar

README.adoc, src/main/resources/META-INF/plugin.xml
just added a link to the JetBrains support on how to switch JDKs. This helped me to resolve issue #223 for me and so it might also help others.
=> added hint to readme regarding #223

src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocUtil.java, src/main/resources/org/asciidoc/intellij/editor/javafx/pickSourceLine.js, src/main/resources/org/asciidoc/intellij/editor/javafx/processLinks.js
=> Support for relative path links in preview html.

FEATURES.adoc, src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java
In addition to the listed aims, I've added the ability to reset zoom using Ctrl and the middle mouse button.
=> Fix #199 - Support zoom in preview window

FEATURES.adoc, src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java, src/main/resources/org/asciidoc/intellij/editor/javafx/processImages.js, src/main/resources/plantuml-png-patch.rb
=> Save pictures from preview, fix #245

src/main/java/org/asciidoc/intellij/AsciiDoc.java
=> inject absolute location of .asciidoctorconfig file #280

src/main/java/org/asciidoc/intellij/AsciiDoc.java
=> support for '.adoc' extension of .asciidoctorconfig file #293

src/main/java/org/asciidoc/intellij/actions/asciidoc/DocumentWriteAction.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/FormatAsciiDocAction.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeTitle.java, src/test/java/org/asciidoc/intellij/actions/asciidoc/MakeTitleTest.java
=> resolves #341 preserve cursor position and selection when toggling title

FEATURES.adoc, src/main/java/org/asciidoc/intellij/inspections/AsciiDocListingStyleInspection.java, src/main/java/org/asciidoc/intellij/quickfix/AsciiDocConvertMarkdownListing.java, src/main/resources/META-INF/plugin.xml, src/main/resources/inspectionDescriptions/AsciiDocListingStyleInspection.html, src/test/java/org/asciidoc/intellij/inspections/AsciiDocListingStyleInspectionTest.java, testData/inspections/listing/markdownListing-after.adoc, testData/inspections/listing/markdownListing.adoc
=> Add markdown listing style inspection and quickfix #297

src/main/resources/META-INF/pluginIcon.svg
=> Resolves #356: Add plugin logo

src/main/resources/org/asciidoc/intellij/editor/javafx/darcula.css
**Before :**
**After the code style change**
=> Fix pre background color

src/main/resources/kroki-extension.rb
=> resolves #365 apply_subs only takes two arguments

src/main/resources/kroki-extension.rb, src/test/java/org/asciidoc/intellij/AsciiDocTest.java
Enable RackDiag, PacketDiag, Vega, Vega-Lite and WaveDrom support when using Kroki.
=> Add support for PacketDiag, RackDiag, Vega, Vega-Lite and WaveDrom

src/main/resources/kroki-extension.rb
as per @Mogztter to address Kroki extension missing attributes
=> Fix for issue #509

src/main/java/org/asciidoc/intellij/ui/SplitFileEditor.java
=> fix AsciiDocSplitEditor to return file / fix #518

doc/contributors-guide/modules/ROOT/pages/coder/building-and-running.adoc, doc/contributors-guide/modules/ROOT/pages/coder/debugging-and-logging.adoc, doc/contributors-guide/modules/ROOT/pages/coder/lexing-and-parsing.adoc, doc/contributors-guide/modules/ROOT/pages/coder/preview.adoc, doc/contributors-guide/modules/ROOT/pages/coder/releasing-plugin.adoc, doc/contributors-guide/modules/ROOT/pages/coder/setup-environment.adoc, doc/contributors-guide/modules/ROOT/pages/contribute-as-a-writer.adoc, doc/contributors-guide/modules/ROOT/pages/docs/change-documentation-theme.adoc, doc/contributors-guide/modules/ROOT/pages/docs/change-startpage.adoc, doc/contributors-guide/modules/ROOT/pages/docs/edit-documentation-content.adoc, doc/contributors-guide/modules/ROOT/pages/docs/writing-user-documentation.adoc, doc/contributors-guide/modules/ROOT/pages/user/add-eap-repository-to-ide.adoc, doc/contributors-guide/modules/ROOT/pages/user/subscribe-to-new-releases.adoc, doc/users-guide/modules/ROOT/pages/faq/could-not-find-dot-executable.adoc, doc/users-guide/modules/ROOT/pages/features.adoc, doc/users-guide/modules/ROOT/pages/features/advanced/asciidoclet.adoc, doc/users-guide/modules/ROOT/pages/features/advanced/stylesheets.adoc, doc/users-guide/modules/ROOT/pages/features/editor.adoc, doc/users-guide/modules/ROOT/pages/features/preview/diagrams.adoc, doc/users-guide/modules/ROOT/pages/features/preview/jcef-preview.adoc, doc/users-guide/modules/ROOT/pages/recommended-settings.adoc, src/main/java/org/asciidoc/intellij/actions/asciidoc/AsciiDocAction.java, src/main/java/org/asciidoc/intellij/actions/editorAction/AsciiDocPasteImageHandler.java, src/main/java/org/asciidoc/intellij/annotator/ExternalAnnotator.java, src/main/java/org/asciidoc/intellij/builder/AsciiDocTargetScopeProvider.java, src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java, src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java, src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditorProvider.java, src/main/java/org/asciidoc/intellij/indexer/AsciiDocTodoIndexer.java
…c comments
* Resolved typos, grammar and punctuation issues.
* Additional reworded some sections to improve their clarity.
=> Resolved typos and wording issues inside the documentation and javadoc comments

doc/users-guide/modules/ROOT/pages/features/advanced/antora.adoc
Apache Camel and Apache Camel Kafka Connector added to "Example Projects" section.
If yes, please describe the breaking change:
**Please try to ensure:**
- When resolving a specific issue, reference it in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)
- Existing tests should pass: https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html
- Try to add new or update tests. Maintainers will help new contributors.
- Update the feature documentation: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/modu …
=> Added Apache Camel example projects.

src/main/java/org/asciidoc/intellij/AsciiDoc.java, src/main/java/org/asciidoc/intellij/AsciiDocDocumentationProvider.java, src/main/java/org/asciidoc/intellij/AsciiDocExtensionService.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/CreateHtmlAction.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/CreatePdfAction.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/PasteImageAction.java, src/main/java/org/asciidoc/intellij/annotator/ExternalAnnotator.java, src/main/java/org/asciidoc/intellij/asciidoc/AntoraIncludeAdapter.java, src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java, src/main/java/org/asciidoc/intellij/editor/browser/BrowserPanel.java, src/main/java/org/asciidoc/intellij/editor/notification/AntoraNotificationProvider.java, src/main/java/org/asciidoc/intellij/findUsages/AsciiDocIdReferencesSearch.java, src/main/java/org/asciidoc/intellij/findUsages/AsciiDocJavaReferencesSearch.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocFileReference.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocUtil.java, src/main/java/org/asciidoc/intellij/template/AsciiDocTemplateContextType.java, src/test/java/org/asciidoc/intellij/AsciiDocExtensionServiceTest.java, src/test/java/org/asciidoc/intellij/actions/asciidoc/ImageMacroAttributeServiceTest.java
~~If yes,~~ please describe the breaking change:
This shouldn't cause any breaking changes most changes were internally or are invoked by Intellij.
But I suggest you do some testing yourself and see if problems do occur.
_resolved deprecations_
* `Project.getBaseDir`
* `CacheManager.SERVICE.getInstance`
* `TemplateContextType.isInContext`
*  `AbstractDocumentationProvider.getCustomDocumentationElement`
_cleanup_
* extracted extension handling from `AsciiDoc` class into `AsciiDocExtensionService`
* cleaned up syntax
* added additional null checks
* added tests
* aligned parameters of function declarations
* removed empty lines
_NOTE:_ Most of …
=> resolved various deprecations and some cleanup

src/main/java/org/asciidoc/intellij/quickfix/AsciiDocCreateMissingFile.java
I
**Please try to ensure:**
- When resolving a specific issue, reference it in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)
- Existing tests should pass: https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html
- Try to add new or update tests. Maintainers will help new contributors.
all tests are green.
I tried to create a new one, but didn't understand the old `AsciiDocCreateMissingFileInspectionTest`
- Update the feature documentation: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/modules/ …
=> fix #575 create missing file inspection for drawio

src/main/java/org/asciidoc/intellij/psi/AsciiDocBlockMacro.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocFileReference.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocInlineMacro.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocUtil.java
If yes, please describe the breaking change:
**Please try to ensure:**
- When resolving a specific issue, reference it in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)
- Existing tests should pass: https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html
- Try to add new or update tests. Maintainers will help new contributors.
- Update the feature documentation: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/modules/ROOT/pages/features/
=> Simple code cleanup

doc/users-guide/modules/ROOT/nav.adoc, doc/users-guide/modules/ROOT/pages/features/keymap.adoc
Added most important shortcuts for Windows/Linux users. If there are no changes needed, I'll update the file with shortcuts for Mac users.
=> docs-565: add keymap for Windows/Linux users

build.gradle, src/main/java/org/asciidoc/intellij/actions/asciidoc/ImageMacroAttributeService.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/MacroAttribute.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/MacroAttributeService.java, src/test/java/org/asciidoc/intellij/actions/asciidoc/MacroAttributeServiceTest.java, src/test/java/org/asciidoc/intellij/actions/asciidoc/MacroAttributeTest.java, src/test/java/org/asciidoc/intellij/conventions/MethodConventionsTest.java
If yes, please describe the breaking change:
**Please try to ensure:**
- When resolving a specific issue, reference it in the PR's title (e.g. `fix #xxx`, where "xxx" is the issue number)
- Existing tests should pass: https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/building-and-running.html
- Try to add new or update tests. Maintainers will help new contributors.
- Update the feature documentation: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/modules/ROOT/pages/features/
=> Refactor of MacroAttribute

doc/users-guide/modules/ROOT/pages/quick-start.adoc
After creating the pull request, Travis CI will run some automated tests.
=> fix minor typo

src/main/resources/liveTemplates/AsciiDocLiveTemplates.xml
No updated docs, because live templates are not part of the docs.
No updated tests, because live tempaltes are not part of the test spec
=> fix #609: add block and paragraph admonition live template

.github/PULL_REQUEST_TEMPLATE.md
It seems that Travis is not the current runner of the CI. Change the PR template to be less specific about that, then it will not get out-of-date so easily.
After creating the pull request, Travis CI will run some automated tests.
=> Do not be specific about the CI

doc/contributors-guide/modules/ROOT/pages/coder/lexing-and-parsing.adoc, doc/contributors-guide/modules/ROOT/pages/coder/preview.adoc, doc/contributors-guide/modules/ROOT/pages/coder/releasing-plugin.adoc, doc/users-guide/modules/ROOT/pages/faq/javafx-initialization-stuck.adoc, doc/users-guide/modules/ROOT/pages/installation.adoc, src/main/java/org/apache/geronimo/gshell/io/SystemOutputHijacker.java, src/main/java/org/asciidoc/intellij/AsciiDoc.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/FormatAsciiDocAction.java, src/main/java/org/asciidoc/intellij/annotator/ExternalAnnotator.java, src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java, src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java, src/main/java/org/asciidoc/intellij/lexer/asciidoc.flex, src/main/java/org/asciidoc/intellij/parser/AsciiDocParserImpl.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocLink.java, src/main/java/org/asciidoc/intellij/quickfix/AsciiDocConvertMarkdownHeading.java, src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettings.java, src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettingsForm.java, src/main/java/org/asciidoc/intellij/ui/CreateTableDialog.java, src/main/resources/inspectionDescriptions/AsciiDocXrefWithNaturalCrossReference.html, src/main/resources/intentionDescriptions/AsciiDocAdmonitionToBlockIntention/description.html, src/main/resources/org/asciidoc/intellij/editor/javafx/scrollToElement.js, src/main/resources/org/asciidoc/intellij/editor/jeditor/preview.css, src/test/java/org/asciidoc/intellij/actions/asciidoc/MakeBoldTest.java, src/test/java/org/asciidoc/intellij/lexer/AsciiDocLexerTest.java, src/test/java/org/asciidoc/intellij/psi/AntoraVersionDescriptorTest.java
After creating the pull request, Travis CI will run some automated tests.
=> Fix various typos

src/main/java/org/asciidoc/intellij/codeStyle/AsciiDocCodeStyleSettings.java, src/main/java/org/asciidoc/intellij/codeStyle/AsciiDocCodeStyleSettingsProvider.java, src/main/java/org/asciidoc/intellij/codeStyle/AsciiDocLanguageCodeStyleSettingsProvider.java, src/main/java/org/asciidoc/intellij/formatting/AsciiDocBlock.java, src/main/resources/samples/BLANK_LINES_SETTINGS.adoc
=> Additional reformat option for spaces between headings #428

doc/users-guide/modules/ROOT/pages/features.adoc
Sorry for editing "per default" if it was intended so. It just kills me not to edit it.
=> Reading the docs, fixing typos

doc/users-guide/modules/ROOT/pages/features/preview.adoc
Line 16 possible typo: "preview and _SAVE_, _SERVER_ and _SECURE_ remote content".
=> Fixed some typos

doc/users-guide/modules/ROOT/pages/features/editor.adoc
Fixed several typos, fixed formatting in a couple of places including ` \[source], \[quote] or \[verse]`, edited Grazie section with up to date information, some clarity enhancements in markdown refactoring segment and include directives segment
=> Typos, formatting, calrity

doc/users-guide/modules/ROOT/pages/features/preview/source-highlighting.adoc
Also, one line didn't have the note number but was in the code.
=> The number notes were not visible

src/main/java/org/asciidoc/intellij/actions/ConvertToAsciiDocAction.java, src/main/java/org/asciidoc/intellij/ui/OverwriteFileDialog.java
=> Fix #763: Add dialog to confirm file overwrite if it exists.

README.adoc
This advertises Hacktoberfest in the readme and provides a link to Hacktoberfest issues.
=> advertise hacktoberfest in readme and reference new label

.github/workflows/build.yml
Let's see if the results compare better now
=> Just another qodana test PR

.github/workflows/website.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
=> Set permissions for GitHub actions

doc/users-guide/modules/ROOT/pages/features/advanced/multimodule.adoc
Alternatively "to be added".
- [] I have updated the [documentation](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/users-guide/modules/ROOT/pages/features/) to reflect the changes introduced by this PR.
- [] I have added tests to cover the changes in the code.
=> Update doc phrasing

CHANGELOG.adoc, src/main/java/org/asciidoc/intellij/highlighting/AsciiDocColorSettingsPage.java
=> Fix: #1105: Cannot change the colour scheme for inline macros

src/main/resources/liveTemplates/AsciiDocLiveTemplates.xml
=> add php source snippet

CHANGELOG.adoc, src/main/resources/jsonSchemas/antoraComponentSchema.json, src/main/resources/jsonSchemas/antoraPlaybookSchema.json
Closes #1140
Admits _more_ YAMLs as valid. Therefore, not technically breaking.
- ❓️ Are there any tests for the schemas? Where?
=> antora: Support fallback versions

doc/users-guide/modules/ROOT/pages/features/advanced/multimodule.adoc
Hi there, thanks for the very useful plugin!
Just spotted a small typo in the documentation and thought I'd directly correct it.
I'm not sure if such tiny PRs are useful/welcome.
Either way, thanks again for the amazing work you do.
=> Fix typo in documentation

doc/contributors-guide/modules/ROOT/pages/contribute-as-a-writer.adoc
While reading through the contribution guidelines for my last tiny PR, I stumbled across a phrase that confused me a bit and took me several times of re-reading to understand what it was intended to express. This is the line I struggled with:
"With this knowledge, writers can choose the how-to to change the content they want to change."
I proposed a rephrasing that expresses the same intention a bit more clearly (hopefully).
=> Fix typo & Rephrase sentence for clarity

src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java, src/main/java/org/asciidoc/intellij/editor/jcef/AsciiDocJCEFHtmlPanel.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocFileUtil.java
URI for a Windows path `C:/foo/bar` reports scheme as `C`.
It's not the best or elegant solution but in my opinion simple. In my use case I am having .asciidoctorconfig to define paths using asciidoctorconfigdir variable which will give me an absolute path. Using that works with includes but not with xrefs in the IDE preview and I get warnings like:
```
WARN - #o.a.i.e.j.AsciiDocJCEFHtmlPanel - won't open URI as it might be unsafe: C:/foo/bar/project/my-doc.html
```
I haven't been able to test this change yet but I want to open the …
=> Open links to Windows absolute paths from xrefs.

doc/contributors-guide/modules/ROOT/pages/user/add-eap-repository-to-ide.adoc
Updated some words in add-eap-repository-to-ide.adoc os it sounds better to the reader(User)
=> [Fix] Made add-eap-repository-to-ide.adoc sound better.

doc/contributors-guide/modules/ROOT/pages/coder/releasing-plugin.adoc
=> [Fix] Made releasing-plugin.adoc sound better. 

doc/contributors-guide/modules/ROOT/pages/docs/change-startpage.adoc, doc/contributors-guide/modules/ROOT/pages/docs/edit-documentation-content.adoc
=> [Fix] Made the Documentation sound better

src/main/java/org/asciidoc/intellij/psi/AsciiDocBlockMacro.java, src/main/java/org/asciidoc/intellij/psi/AsciiDocInlineMacro.java, src/main/resources/diagram-placeholder.rb, src/main/resources/kroki-extension.rb
=> Add support for D2 and DBML diagrams introduced in Kroki 0.19.0

doc/users-guide/modules/ROOT/pages/features/advanced/asciidoctorconfig-file.adoc
=> Make example less confusing

doc/users-guide/modules/ROOT/pages/features/advanced/validation-cicd.adoc
=> Fix a typo in validation-cicd.adoc

doc/users-guide/modules/ROOT/pages/features/advanced/spring-rest-docs.adoc
=> Update rest-docs reference url

build.gradle, src/main/java/org/asciidoc/intellij/actions/AsciiDocCreateFileFromAction.java, src/main/java/org/asciidoc/intellij/actions/ConvertToAsciiDocAction.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/AsciiDocAction.java, src/main/java/org/asciidoc/intellij/actions/asciidoc/ToggleSoftWrapsAction.java, src/main/java/org/asciidoc/intellij/actions/editorlayout/BaseChangeSplitLayoutAction.java
=> Remove deprecated APIs

src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java
This PR should fix https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1413
Not tested yet.
=> Update AsciiDocDownloaderUtil.java to fix #1413

config/checkstyle/checkstyle.xml, src/main/java/org/asciidoc/intellij/arch/Arch.java, src/main/java/org/asciidoc/intellij/arch/OS.java, src/main/java/org/asciidoc/intellij/arch/Platform.java, src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java, src/main/java/org/asciidoc/intellij/download/PandocInfo.java
The code has an issue where the archive file contents do not match the expected values.
In the process I refactored the code to better understand it and (hopefully) make it more readable.
(Closes #1429)
=> Refactor pandoc download code

.github/workflows/build.yml, .github/workflows/release.yml, build.gradle
=> Replaced Java 11 references with Java 17.

src/main/resources/liveTemplates/AsciiDocLiveTemplates.xml
- [ x ] Feature
- [ x ] No
Add new GOlang code snippet
=> add GOlang source snippet

src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanelProvider.java, src/test/java/org/asciidoc/intellij/AsciiDocWrapperTest.java
=> Enable JavaFX on M1/M2 Macs

.sdkmanrc
Developers often work on several projects, each with their own specific Java version requirements.
SDKMAN makes it easy to switch between different projects and always be using the correct /
required version of Java. SDKMAN's .sdkmanrc file is automatically detected and used by IntelliJ to
ensure the correct JDK is used when opening a project.
=> Install Amazon Corretto JDK 17 via SDKMAN!

CHANGELOG.adoc, build.gradle.kts, config/checkstyle/checkstyle.xml, src/main/java/org/asciidoc/intellij/AsciiDocWrapper.java, src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java, src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettingsForm.form, src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettingsForm.java, src/main/resources/AsciiDocBundle.properties, src/main/resources/diagram-placeholder.rb
=> Add additional asciidoctorj-diagram extentions
