- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeMono.java
The method returned a wrong string. This commit fixes this and makes it
consistent.
> Fix `getName()` of `MakeMono` class

- src/main/resources/liveTemplates/AsciiDocLiveTemplates.xml
This commit improves some live templates by removing static text and
replacing it with variables. This is consistent with some other of the
existing templates and makes editing a more pleasurable experience.
> Improve Live Templates

- src/main/java/org/asciidoc/intellij/actions/asciidoc/CreateTableAction.java
- src/main/java/org/asciidoc/intellij/ui/CreateTableDialog.java
This commit changes the `CreateTableDialog`, so that it allows to type
the title of the table directly. This replaces the checkbox 'use title'
that was used before. Leaving the input empty is equal to not ticking
the checkbox.
> Add Title to Create Table Dialog

- src/main/java/org/asciidoc/intellij/AsciiDoc.java
- src/main/java/org/asciidoc/intellij/MayLineTreeProcessor.java
- src/main/java/org/asciidoc/intellij/editor/AsciiDocHtmlPanel.java
- src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java
- src/main/java/org/asciidoc/intellij/editor/AsciiDocSplitEditor.java
- src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java
- src/main/java/org/asciidoc/intellij/editor/jeditor/JeditorHtmlPanel.java
- src/main/resources/org/asciidoc/intellij/editor/javafx/processLinks.js
- src/main/resources/org/asciidoc/intellij/editor/javafx/scrollToElement.js
- src/main/resources/sourceline-treeprocessor.rb
This PR borrows ideas from Markdown plugin to open links in new browser windows and scroll the preview to the current cursor position. Both features load some extra JavaScript into the preview. 
Closing #130. Closing #121. 
Adding source code lines to the HTML is done using a (Ruby) TreeProcessor (like it is done in AsciidocFX editor). 
There is a limitation to this: The source line is in the HTML output only once per DIV. That means only once per text block. A long list that will span multiple items is still one block. Therefore the scrolling is a bit bumpy. 
I'm wondering if this is good enough, or if more source line information can be added to the HTML, or if I could use some interpolation algorithm, or something completely different.
> autoscrolling JavaFX preview and links opening in a new browser window

- .idea/misc.xml
- src/main/java/org/asciidoc/intellij/actions/asciidoc/FormatAsciiDocAction.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeBold.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeItalic.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeLink.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeMono.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeStrikethrough.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/MakeTitle.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/SimpleFormatAsciiDocAction.java
- src/test/java/org/asciidoc/intellij/actions/asciidoc/MakeBoldTest.java
- src/test/java/org/asciidoc/intellij/actions/asciidoc/MakeLinkTest.java
- src/test/java/org/asciidoc/intellij/actions/asciidoc/MakeTitleTest.java
This tries to fix issue #123. 
The new method FormatAsciiDocAction#isWord() tries to capture Asciidoc's "unconstrained quotes" logic. 
I'm relying on Java 8 `\p{IsAlphabetic}` to identify Unicode characters. 
Comments welcome. I could upload a preview release next week once I am connected to a fast internet again. 
@bodiam, @mojavelinux - please let me know if this looks like what was intended.
> use constrained quotes when possible

- src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java
- src/main/java/org/asciidoc/intellij/editor/javafx/darcula.css
This is a preview for darcula support, intended to close #122.
@bodiam - do you want to give it a try? A preview is available here: https://github.com/ahus1/asciidoctor-intellij-plugin/releases/tag/0.16.0.3
I've implemented a darcula.css that overrides the default CSS classes to make them "dark". I hope I've caught the most important ones. 
If I've missed some classes, please post a small asciidoc snipped showing what is not working yet.
> adding darcula CSS theme for JavaFX

- src/main/java/org/asciidoc/intellij/AsciiDoc.java
- src/main/java/org/asciidoc/intellij/actions/AsciiDocAction.java
- src/main/java/org/asciidoc/intellij/editor/AsciiDocHtmlPanelProvider.java
- src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java
- src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java
- src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanelProvider.java
- src/main/java/org/asciidoc/intellij/editor/jeditor/JeditorHtmlPanelProvider.java
I implemented this feature as discussed in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/162
I only tested it on OSX!
There might be an issue under windows (colons) (JavaFxHtmlPanel, line 225:  return Paths.get(base).relativize(file).toString();). 
I set the outdir attribute so that the .asciidoctor directory gets created in the temp directory as well
The temp dir gets created whenever an editor is opened, so switching between Swing and JavaFX is possible.
I couldn't figure out when the AsciiDocAction is used. I pass null as the imagesPath parameter in actionPerformed...
> create temp image dir and set outdir to this dir (JavaFX Panel only)

- src/main/java/org/asciidoc/intellij/AsciiDoc.java
- src/main/java/org/asciidoc/intellij/editor/AsciiDocPreviewEditor.java
- src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxCouldBeEnabledNotificationProvider.java
- src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettings.java
- src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettingsForm.form
- src/main/java/org/asciidoc/intellij/settings/AsciiDocPreviewSettingsForm.java
- src/main/java/org/asciidoc/intellij/settings/AttributeTable.java
- src/main/java/org/asciidoc/intellij/settings/AttributeTableItem.java
- src/test/java/org/asciidoc/intellij/AsciiDocTest.java
Hello!
I added the possibility to configure attribute entries in the settings panel. We needed this feature because we set attributes in our maven builds for include paths and some other attributes depending on the environment which of course did not work in the preview.
Now we can configure the asciidoc attributes in the plugin:
> Configure attribute entries in settings panel

- CHANGELOG.adoc
- build.gradle
> update jruby to fix failing assertion when creating PDF

- FEATURES.adoc
- src/main/java/org/asciidoc/intellij/AsciiDoc.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/CreateHtmlAction.java
- src/main/java/org/asciidoc/intellij/actions/asciidoc/CreatePdfAction.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/org/asciidoc/intellij/AsciiDocTest.java
> fix #349 create HTML from IDE using an editor action

- src/main/resources/org/asciidoc/intellij/editor/javafx/coderay-darcula.css
- src/main/resources/org/asciidoc/intellij/editor/javafx/darcula.css
This PR fixes some remaining visual issues when the darcula theme is active.
For `kbd` elements, e.g. `kbd:[Alt+F11]`
For code blocks styled with coderay having line numbers :
This is a direct followup to #364
> Fix darcula kbd and coderay line numbers background color

- src/main/java/org/asciidoc/intellij/lexer/asciidoc.flex
- src/test/java/org/asciidoc/intellij/inspections/AsciiDocLinkResolveInspectionTest.java
- src/test/java/org/asciidoc/intellij/lexer/AsciiDocLexerTest.java
- testData/inspections/linkResolve/fileDoesntExist.adoc
- testData/inspections/linkResolve/localAnchor.adoc
* I'm not 100% sure if this is the correct approach; other options I considered were either modifying the TITLE_TOKEN regex (to check it's not a table row) or patching this during the parsing stage (but couldn't figure out how that would work without adding lots of complexity). All tests pass, so I assume this still parses headings correctly for all the relevant cases.
* The image-with-anchor-in-a-table-cell is the original issue I ran into; hence that …
> Table with vertical alignment

- CHANGELOG.adoc
- build.gradle
- src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java
If yes, please describe the breaking change:
The answer to the question above is 'maybe'. This shouldn't be a breaking change, but Robert Panzer and I did some work on the image ouput directory selection mechanism which may have an influence on the preview view. Safe made in particular might be something to check.
> Bump asciidoctor-diagram version to 2.0.5

- src/main/java/org/asciidoc/intellij/actions/asciidoc/ImageMacroAttributeService.java
- src/test/java/org/asciidoc/intellij/actions/asciidoc/ImageMacroAttributeServiceTest.java
- src/test/java/org/asciidoc/intellij/actions/asciidoc/MacroAttributeServiceTest.java
removing verify() from from tests as it depends on the internal implementation.
Use existing lightweight objects to instead of Mockito to improve readability.
> Improving readability & reducing internal knowledge in tests

- .github/PULL_REQUEST_TEMPLATE.md
Change in the PR template. As requested (#564), it leaves less open ends, encourages the contributors to go over and confirm the guidelines, and hides some of the previously visible instructions. I'll probably use something similar myself. :)
Some portions are loosely based [TalAter's](https://github.com/TalAter/open-source-templates) template.
> fix #564: update PR template

- doc/contributors-guide/modules/ROOT/pages/coder/upgrading-asciidoctor.adoc
I was checking the docs and I found 2 improvements in `upgrading-asciidoctor.adoc`
1. DONE: Use upper case in the numbered lost, same as in the other documents in the docs.
2. NEED CONFIRMATION: the sentence at the bottom did not feel right, I applied some minimal changes. Let me know if these are right.
*I hope so* :crossed_fingers:
*N/A*
*N/A*
*N/A*
> Use upper case in numbered list

- src/main/resources/AsciiDocBundle.properties
The correct terminology is "passthrough content" as defined by the AsciiDoc language documentation (see https://github.com/asciidoctor/asciidoc-docs/blob/main/modules/subs/pages/prevent.adoc#passthroughs). I added a missing "h" in through and removed the space between "pass" and "through".
> fix typos in language bundle for passthrough content

- CHANGELOG.adoc
- src/main/java/org/asciidoc/intellij/AsciiDocWrapper.java
This now shows an error message in the preview is loading of the stylesheet fails:
> Add error message in preview when loading the custom stylesheet fails (#1076)

- src/main/java/org/asciidoc/intellij/AsciiDocCommenter.java
I tested the described wanted behaviour in #601. Text is now commented out with leading "// " and commented out text is uncommented correctly for comments with old prefix ("//test") as well as with new prefix ("// test"). But I don't know how to write a test for that because the affected class AsciiDocCommenter.java doesn't have a test class (yet).
> fix #601 : add space for line comment prefix

- .github/workflows/docs.yml
Removing the Gradle plugin should prevent downloading all dependencies and speed up the build.
> streamline Quodana spell checking and avoid download of dependencies

- .github/workflows/docs.yml
- doc/users-guide/modules/ROOT/pages/features/advanced/validation-cicd.adoc
- qodana.yaml
> Use latest mechanism to auto-download plugins for Qodana

- build.gradle
- src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java
I would like to upgrade asciidoctorj-diagram to 2.2.17 and asciidoctorj-diagram-plantuml to 1.2023.13 in order to use the latest fixes and features from the IntelliJ plugin.
> Upgrade Asciidoctorj Diagram and PlantUML Dependencies

- CHANGELOG.adoc
typo in 6b64c55a (Prevent decoder exception when
filename contains a percentage sind in IntelliJ 2024.1 EAP (#1580), 2024-03-23 alexander.schwartz)
Thanks for the update!
> fixing changelog

- doc/users-guide/modules/ROOT/pages/features/preview.adoc
The main item fixed is replacing `SAVE` with `SAFE`.
> Fix typos and improve some grammar + punctuation.

- CHANGELOG.adoc
- src/main/resources/META-INF/plugin.xml
Closes #1778
I don't know. Hopefully not.
---
CLion 2025.1 EAP does not work with AsciiDoc - it blocks typing in Python scripts. Issue reported here: https://youtrack.jetbrains.com/issue/CPP-43240 .
The fix I'm sending was proposed by Jetbrains support in https://youtrack.jetbrains.com/issue/CPP-43240/Cannot-type-more-than-1-letter-in-Python-scripts#focus=Comments-27-11542597.0-0 .
I've locally tested the fix and it works for me (at least regarding not breaking Python coding).
Credit goes to Alexander Karaev from JB.
> Fix for CLion 2025.1 EAP
